### ISSUE TITLE
Black background when Presented VC is NavBar Controller Child

### ISSUE THREAD

**Issue by bishalg** [TotemTraining/DimBackground#1]
We will have following output - ie black background 

![simulator screen shot may 23 2016 7 40 02 am](https://cloud.githubusercontent.com/assets/805689/15458447/df1c3044-20b9-11e6-9ece-a33f614fd971.png)

When the ViewController stack is a child of Navigation Controller 
<img width="1013" alt="screen shot 2016-05-23 at 7 40 52 am" src="https://cloud.githubusercontent.com/assets/805689/15458453/f76e64aa-20b9-11e6-9124-a1f3c3c0f5f3.png">

**Comment by kusalshrestha** [comment]
You can change the presentation style of the NavigationController to "Over Current Context" or "Over Full Screen"
<img width="1280" alt="screen shot 2016-05-23 at 3 32 12 pm" src="https://cloud.githubusercontent.com/assets/10921013/15467007/eae0a864-20fb-11e6-83bb-84adbb114c2f.png">

**Comment by Chris-BMA** [comment]
See answer above from kusalshrestha.  Thanks!
